### ISSUE TITLE
sqlstate error with postgres: catalog is missing 10 attribute(s) for relid 16468

### ISSUE THREAD

**Issue by connor11528** [kirschbaum-development/laravel-test-runner-container#18]
Hi there,

I'm trying to use this for my project but getting an error when executing the PHPunit tests. When I run it getting error saying catalog is missing attributes:

```
| 2) Tests\Feature\CandidateUpdateProfileTest::it_should_not_be_accessible_to_inactivated_users
| Illuminate\Database\QueryException: SQLSTATE[XX000]: Internal error: 7 ERROR:  catalog is missing 10 attribute(s) for relid 16468 (SQL: drop table "migrations","users","password_resets","job_listings","action_events","tags","taggables","work_histories","education","projects","user_invitations","posts","company_locations","companies","employers","telescope_entries","telescope_entries_tags","telescope_monitoring","diffbot_companies","company_watchlists","subscriptions","sessions","cache","departments","skills","candidate_skills","job_locations","job_boards" cascade)
...
Caused by
| Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[XX000]: Internal error: 7 ERROR:  catalog is missing 10 attribute(s) for relid 16468
```

This is my file for GitHub Actions:

```
name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run Testsuite
        run: vendor/bin/phpunit
```

I have environment variables defined in `.env.ci` as outlined in [this blog post](https://kirschbaumdevelopment.com/insights/laravel-github-actions). This is the actual test that's trying to run and failing:

```
class CandidateUpdateProfileTest extends TestCase
{
    use DatabaseMigrations;

    /** @test */
    public function it_should_check_user_is_logged_in()
    {
        $this->markTestSkipped('skipping candidade profile test');

        $response = $this->get('/candidates/2/edit');

        $response->assertStatus(302);
    }

    /** @test */
    public function it_should_not_be_accessible_to_inactivated_users()
    {
        $this->markTestSkipped('skipping candidade profile test');

        $user = factory(User::class)->states('inactive')->create();

        $response = $this->actingAs($user)->get('/candidates/'.$user->id.'/edit');

        $response->assertSee('Thanks for applying. Your account is not activated yet');
    }
```

Is there something I'm missing here? When running PHPunit tests locally the test skip as expected.
