### ISSUE TITLE
Error: Stuck on checkout

### ISSUE THREAD

**Issue by GamerClassN7** [kirschbaum-development/laravel-test-runner-container#44]
every time i try to run workflow i get this error 

![image](https://github.com/kirschbaum-development/laravel-test-runner-container/assets/22167469/170a3c68-5ffe-4772-8e0e-7a35532fa3fc)

**Comment by luisdalmolin** [comment]
This doesn't seem related to this container, but if you want any help, please post your full workflow. I'm closing this for now, but feel free to reopen with the full workflow

**Comment by GamerClassN7** [comment]
@luisdalmolin  after switching checkout to v2 i get little-bit different error:

```log
/run/act/actions/actions-checkout@v2/dist/index.js:16111
const { access, appendFile, writeFile } = fs_1.promises;
        ^
TypeError: Cannot destructure property `access` of 'undefined' or 'null'.
    at Object.665 (/run/act/actions/actions-checkout@v[2](https://git.steelants.cz/SteelAnts/LAR_Mujsport/actions/runs/14#jobstep-1-2)/dist/index.js:16111:48)
    at __webpack_require__ (/run/act/actions/actions-checkout@v2/dist/index.js:22:[3](https://git.steelants.cz/SteelAnts/LAR_Mujsport/actions/runs/14#jobstep-1-3)0)
    at Object.[4](https://git.steelants.cz/SteelAnts/LAR_Mujsport/actions/runs/14#jobstep-1-4)70 (/run/act/actions/actions-checkout@v2/dist/index.js:1189[5](https://git.steelants.cz/SteelAnts/LAR_Mujsport/actions/runs/14#jobstep-1-5):17)
    at __webpack_require__ (/run/act/actions/actions-checkout@v2/dist/index.js:22:30)
    at Object.198 (/run/act/actions/actions-checkout@v2/dist/index.js:458[6](https://git.steelants.cz/SteelAnts/LAR_Mujsport/actions/runs/14#jobstep-1-6):2[7](https://git.steelants.cz/SteelAnts/LAR_Mujsport/actions/runs/14#jobstep-1-7))
    at __webpack_require__ (/run/act/actions/actions-checkout@v2/dist/index.js:22:30)
    at startup (/run/act/actions/actions-checkout@v2/dist/index.js:37:19)
    at module.exports.0.requestLog.requestLog (/run/act/actions/actions-checkout@v2/dist/index.js:41:1[8](https://git.steelants.cz/SteelAnts/LAR_Mujsport/actions/runs/14#jobstep-1-8))
    at Object.<anonymous> (/run/act/actions/actions-checkout@v2/dist/index.js:44:[10](https://git.steelants.cz/SteelAnts/LAR_Mujsport/actions/runs/14#jobstep-1-10))
    at Module._compile (internal/modules/cjs/loader.js:654:30)
```

**Comment by luisdalmolin** [comment]
You need to specify the tag in the container definition:

```yaml
on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install composer dependencies
          run: |
            composer install --no-scripts

        - name: Prepare Laravel Application
          run: |
            cp .env.ci .env
            php artisan key:generate

        - name: Run Testsuite
          run: vendor/bin/phpunit tests/
```
