### ISSUE TITLE
permissions issue when compiling assets

### ISSUE THREAD

**Issue by 1stevengrant** [kirschbaum-development/laravel-test-runner-container#45]
I have a GitHub Action configured using PHP 8.2 container

```
on:
  push:
    branches:
      - prod
      - dev
  pull_request:
    branches:
      - dev
      - prod
    types:
      - opened

name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wahlocal_test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-${{ matrix.dependency-version }}-${{ matrix.os }}-${{ hashFiles('composer.json') }}

      - name: Install composer dependencies
        run: |
          composer install --no-scripts
        env:
          COMPOSER_AUTH: '{ "github-oauth": { "github.com": "${{ secrets.PAT }}" }, "http-basic": { "wire-elements-pro.composer.sh": { "username": "xxx", "password": "${{ secrets.WIRE_ELEMENTS_PRO_KEY }}" }, "nova.laravel.com": { "username": "xxx", "password": "${{ secrets.NOVA_KEY }}"}}}'

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Install front-end dependencies
        run: |
          npm install
          npm run build

      - name: Run Testsuite
        run: vendor/bin/pest tests/

```

and I've been running into this error when building the assets in Vite

```
> build
> vite build

vite v4.4.9 building for production...
transforming...
✓ 1[7](https://github.com/1stevengrant/site.com/actions/runs/8829879107/job/24241847106?pr=199#step:7:8)92 modules transformed.
rendering chunks...
EACCES: permission denied, mkdir '/__w/site.com/site.com/public/build'
✓ built in 11.[9](https://github.com/1stevengrant/site.com/actions/runs/8829879107/job/24241847106?pr=199#step:7:10)2s
error during build:
Error: EACCES: permission denied, mkdir '/__w/site.com/site.com/public/build'
Error: Process completed with exit code 1.
```

What's interesting is that it doesn't happen with the 8.1 test runner container and I can't see any real differences between the 2 that could be causing the issue.

Any ideas?
