### ISSUE TITLE
Error: Please make sure the PHP Redis extension is installed and enabled.

### ISSUE THREAD

**Issue by arifulhb** [kirschbaum-development/laravel-test-runner-container#5]
Hi, I am testing a Laravel application with this image, but I am getting this error.

```
Please make sure the PHP Redis extension is installed and enabled.
```

In some places I am using Redis database to store some data which I sync with tasks in a periodical time. All of these is part of the test cases and exactly that time the action fails and throw this error. 

I added this under `services:` after `mysql` and I still get the error. 
```
redis:
    image: redis
    ports:
      - "6379:6379"
```

Do you have any solution to this problem?

TIA
Ariful

**Comment by luisdalmolin** [comment]
Sure, seems like this should be solved by installing the PHP Redis extension. Let me do that.

**Comment by arifulhb** [comment]
> Sure, seems like this should be solved by installing the PHP Redis extension. Let me do that.

Sorry for the late replay. I solved it actually. I added Redis service  and set `REDIS_CLIENT='predis'` and all worked.
```
services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379:6379
```
